---
title: Charles RT - Interaction Designer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@charlesrt.co.uk
description: Interaction designer based in Leeds, currently helping UK government
  design digital services that matter.
baseurl:
url: http://charlesrt.co.uk
social-media-list:
  twitter: https://twitter.com/charles_rt
  github: https://github.com/charlesrt
  medium: https://medium.com/@charlesrt
  linkedin: https://uk.linkedin.com/in/charles-reynolds-talbot-7741b6b7
markdown: kramdown
permalink: "/:year/:month/:title/"
sass:
  sass_dir: _sass
  style: compressed
