# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Charles RT - Interaction Designer
email: hello@charlesrt.co.uk
description: Interaction designer based in Leeds, currently making government digital services better.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://charlesrt.co.uk" # the base hostname & protocol for your site
twitter_username: charles_rt
github_username:  charlesrt

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
